# fly.toml app configuration file generated for cblol-live-bot on 2023-07-03T00:16:26-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cblol-live-bot"
primary_region = "gru"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  LOL_API_KEY="0TvQnueqKa5mxJntVWt0w4LpLfEkrV1Ta8rQBb9Z"
  LOL_API_LANG="pt-BR"
  DEBUG=false

[mounts]
  source="cblol_bot_db"
  destination="/mnt/cblol_bot_db"